version: '3.8'

services:
    mongodb:
        container_name: mongodb
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - db:/data/db
    whatsapp:
        container_name: whatsapp
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PORT=3333
        depends_on:
            - mongodb
        env_file: .env
        ports:
            - 3333:3333
        environment:
            - PORT=3333
            - MONGODB_ENABLED=true
            - MONGODB_URL=mongodb://mongodb:27017
            - WEBHOOK_ENABLED=true
            - WEBHOOK_URL=http://127.0.0.1:3000/webhook/whatsapp
            - LOG_LEVEL=trace
            - RESTORE_SESSIONS_ON_START_UP=true
            - WEBHOOK_ALLOWED_EVENTS=messages
        volumes:
            - ./:/home/node/whatsapp
            - /home/node/whatsapp/node_modules/

volumes:
    db:
